import React from 'react'

import Layout from '../../components/layout'
import Seo from '../../components/seo'

function TermsOfUsePage
() {
  return (
    <Layout>
      <Seo title="Private Policy" />
      <section className="max-w-6xl w-full mx-auto pt-44 text-gray-700">
        <h1 className="mb-11 text-2xl font-medium">Private Policy</h1>
        <p className="mb-11">Adtrics.com takes your right to privacy seriously, and wants you to feel comfortable using our web site. Adtrics ("us", "we", or "our") operates the https://adtrics.com website and the Adtrics application (the "Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. <br /><br /> We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
        <div className="mb-11">
          <h4 className="text-xl font-medium text-san-marino-500 mb-3">1. Definitions</h4>
          <div className="mb-6">
            <p className="font-bold text-black">Personal Data</p>
            <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
          </div>
          <div className="mb-6">
            <p className="font-bold text-black">Usage Data</p>
            <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
          </div>
          <div className="mb-6">
            <p className="font-bold text-black">Cookies</p>
            <p>Cookies are small pieces of data stored on a User’s device. <br /><br /> For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
          </div>
          <div className="mb-6">
            <p className="font-bold text-black">Data Controller</p>
            <p>Data Controller means a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed.</p>
          </div>
          <div className="mb-6">
            <p className="font-bold text-black">Data Processor (or Service Providers)</p>
            <p>Data Processor (or Service Provider) means any person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller. <br /><br />We may use the services of various Service Providers in order to process your data more effectively.</p>
          </div>
          <div className="mb-6">
            <p className="font-bold text-black">Data Subject</p>
            <p>Data Subject is any living individual who is the subject of Personal Data.</p>
          </div>
          <div className="mb-6">
            <p className="font-bold text-black">User</p>
            <p>The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
          </div>
        </div>

        <div className="mb-11">
          <h4 className="text-xl font-medium text-san-marino-500 mb-3">6. Disclosure Of Data</h4>
          <div className="mb-6">
            <p className="font-bold text-black">Business Transaction</p>
            <p className="mb-4">If Adtrics is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
          </div>
          <div className="mb-6">
            <p className="font-bold text-black">Disclosure for Law Enforcement</p>
            <p className="mb-4">Under certain circumstances, Adtrics may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
          </div>
          <div className="mb-6">
            <p className="font-bold text-black">Legal Requirements</p>
            <p className="mb-4">Adtrics may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul className="list-disc list-inside mb-4">
              <li>To comply with a legal obligation</li>
              <li>To protect and defend the rights or property of Adtrics</li>
              <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>To protect the personal safety of users of the Service or the public</li>
              <li>To protect against legal liability</li>
            </ul>
          </div>
        </div>
        
      </section>
    </Layout>
  )
}

export default TermsOfUsePage
